/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas;

import com.mycompany.proyectoblocknotas.Nota.ControladorNota;
import com.mycompany.proyectoblocknotas.Nota.Nota;
import com.mycompany.proyectoblocnotas.Categorias.Categoria;
import com.mycompany.proyectoblocnotas.Categorias.ControladorCategoria;
import com.mycompany.proyectoblocnotas.Historico.ControladorHistorico;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.List;
import java.util.Optional;

/**
 *
 * @author jerem
 */
public final class JpHistorico extends javax.swing.JPanel {
    
   ControladorNota controlNota=new ControladorNota();
    
    
    
    
    
    /**
     * Creates new form JpHistorico
     */
    public JpHistorico() {
        initComponents();
        CargaDatos();
    }
    
    public void CargaDatos(){
        ControladorHistorico h = new ControladorHistorico();
        ControladorCategoria c = new ControladorCategoria();
        List<Categoria> listCat = c.obtenerCategorias();
        List <Nota> hist = h.obtenerNotas();
        jtHistorico = new javax.swing.JTable();

        jtHistorico.setAutoCreateRowSorter(true);

        Object [][] v = new Object[hist.size()][2];
        int cont = 0;
        for (Nota nota : hist) {
            v[cont][0] = nota.getContenido();
            v[cont][1] = nota.getFechaCreacion().toString();
            Optional<Categoria> cat = listCat.stream().filter(e->e.getId()==nota.getIdcategoria()).findFirst();
            if(!cat.isEmpty())
            {
                v[cont][2] = cat.get().getNombre();
            }
            v[cont][2] = "N/A";
            cont++;
        }
        /*
           new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            }
        */
        jtHistorico.setModel(new javax.swing.table.DefaultTableModel(
             v,
            new String [] {
                "Contenido", "Fecha Crecion", "Cataegoria"
            }
        ));

        jScrollPane1.setViewportView(jtHistorico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProceso = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHistorico = new javax.swing.JTable();
        lblhistorico = new javax.swing.JLabel();
        cBoxProceso = new javax.swing.JComboBox<>();
        lblCompletadas = new javax.swing.JLabel();
        lblPendientes = new javax.swing.JLabel();
        CBPendientes = new javax.swing.JComboBox<>();
        CBCompletadas = new javax.swing.JComboBox<>();
        btnCargarCompletadas = new javax.swing.JButton();
        btnCargarPendientes = new javax.swing.JButton();
        btnCargarProceso = new javax.swing.JButton();

        lblProceso.setText("En proceso");
        lblProceso.setToolTipText("");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");

        jtHistorico.setAutoCreateRowSorter(true);
        jtHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtHistorico);

        lblhistorico.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblhistorico.setText("Historico");

        cBoxProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCompletadas.setText("Completadas");

        lblPendientes.setText("Pendientes");

        CBPendientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBCompletadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCargarCompletadas.setText("Cargar");
        btnCargarCompletadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarCompletadasMouseClicked(evt);
            }
        });

        btnCargarPendientes.setText("Cargar");

        btnCargarProceso.setText("Cargar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(lblhistorico))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(CBCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btnCargarCompletadas)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCargarPendientes)
                                    .addComponent(CBPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cBoxProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCargarProceso)
                                        .addGap(66, 66, 66)
                                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar)))))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblhistorico)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCrear)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPendientes)
                            .addComponent(lblCompletadas)
                            .addComponent(lblProceso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarCompletadas)
                            .addComponent(btnCargarPendientes)
                            .addComponent(btnCargarProceso))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBCompletadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        JpCrear jp1 = new JpCrear();
        jp1.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCargarCompletadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarCompletadasMouseClicked

        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarCompletadasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCompletadas;
    private javax.swing.JComboBox<String> CBPendientes;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCargarCompletadas;
    private javax.swing.JButton btnCargarPendientes;
    private javax.swing.JButton btnCargarProceso;
    private javax.swing.JButton btnCrear;
    private javax.swing.JComboBox<String> cBoxProceso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtHistorico;
    private javax.swing.JLabel lblCompletadas;
    private javax.swing.JLabel lblPendientes;
    private javax.swing.JLabel lblProceso;
    private javax.swing.JLabel lblhistorico;
    // End of variables declaration//GEN-END:variables
}
